#!/bin/bash
#sleep 2
#bash -c 'killall xfce4-panel;  /usr/bin/xfce4-panel &'
xrandr --listactivemonitors | grep DP-2-1
output=`echo $?`

# if DP-2-1 exists assume all 3 monitors are connected, otherwise just the laptop monitor
# This has a dependency on the xfpanel-switch, which I installed from source on debian
if [[ $? -eq 0 ]]; then
	/usr/local/bin/xfpanel-switch load /home/brett/.autorandr/work-panel.tar.bz2
else
    /usr/local/bin/xfpanel-switch load /home/brett/.autorandr/work-panel-laptop-only.tar.bz2
fi


